### ISSUE TITLE
无法添加欢迎页

### ISSUE THREAD

**Issue by TucaoNico** [by-syk/NanoIconPack#8]
添加
```
dependencies {
    compile 'com.stephentuso:welcome:1.4.1'
}
```
后，点击`sync`，始终无法下载 `http://jcenter.bintray.com/com/stephentuso/welcome/1.4.1/welcome-1.4.1.pom`。
但是从浏览器打开可以下载。

**Comment by TucaoNico** [comment]
抱歉，还是代理设置的问题，AS的代理设置与Gradle不同，打扰了。
不过如果有小伙伴遇到同样的问题，在gradle.properties中添加你的代理服务器即可：
> HTTP
```
systemProp.https.proxyHost=127.0.0.1
systemProp.http.proxyHost=127.0.0.1 //你的地址
systemProp.https.proxyPort=1087 //你的端口号
```

**Comment by by-syk** [comment]
:thumbsup:
